import PrintLayout from '@/Layouts/PrintLayout';
import { usePage } from '@inertiajs/react';
import { Box, Divider, Stack, Table, TableBody, TableCell, TableHead, TableRow, Typography } from '@mui/material';

const currency = new Intl.NumberFormat('en-US', {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
});

const formatCurrency = (value) => currency.format(Number(value || 0));
const formatDate = (value) => (value ? new Date(value).toLocaleDateString() : '-');
const formatMonth = (value) =>
    value
        ? new Date(`${String(value).slice(0, 10)}T00:00:00`).toLocaleDateString(undefined, {
              year: 'numeric',
              month: 'long',
          })
        : '-';

export default function InvoicePrint({ invoice }) {
    const { admin_app_url } = usePage().props;

    return (
        <PrintLayout
            title={`Invoice ${invoice.invoice_number}`}
            subtitle="Printable invoice voucher"
            backHref={`${admin_app_url}/invoices`}
        >
            <Stack spacing={2}>
                <Stack direction="row" justifyContent="space-between" spacing={2}>
                    <Box>
                        <Typography variant="h5" sx={{ fontWeight: 850 }}>
                            {invoice.branch?.name || 'Super Excellent Wifi Solutions'}
                        </Typography>
                        <Typography variant="body2" color="text.secondary">
                            {invoice.branch?.address || 'Branch address not available'}
                        </Typography>
                        <Typography variant="body2" color="text.secondary">
                            {invoice.branch?.phone || 'Phone not available'}
                        </Typography>
                    </Box>
                    <Box sx={{ textAlign: 'right' }}>
                        <Typography variant="overline" color="text.secondary">
                            Invoice Voucher
                        </Typography>
                        <Typography variant="h6" sx={{ fontWeight: 840 }}>
                            {invoice.invoice_number}
                        </Typography>
                        <Typography variant="body2" color="text.secondary">
                            Issue Month: {formatMonth(invoice.invoice_month)}
                        </Typography>
                        <Typography variant="body2" color="text.secondary">
                            Due Date: {formatDate(invoice.due_date)}
                        </Typography>
                    </Box>
                </Stack>

                <Divider />

                <Stack direction={{ xs: 'column', sm: 'row' }} spacing={2}>
                    <Box sx={{ flex: 1 }}>
                        <Typography variant="overline" color="text.secondary">
                            Bill To
                        </Typography>
                        <Typography sx={{ fontWeight: 760 }}>{invoice.customer?.name || '-'}</Typography>
                        <Typography variant="body2" color="text.secondary">
                            Customer Code: {invoice.customer?.customer_code || '-'}
                        </Typography>
                        <Typography variant="body2" color="text.secondary">
                            Phone: {invoice.customer?.phone || '-'}
                        </Typography>
                        <Typography variant="body2" color="text.secondary">
                            Address: {invoice.customer?.address || '-'}
                        </Typography>
                    </Box>

                    <Box sx={{ flex: 1 }}>
                        <Typography variant="overline" color="text.secondary">
                            Service Details
                        </Typography>
                        <Typography variant="body2" color="text.secondary">
                            Package: {invoice.package_name || '-'}
                        </Typography>
                        <Typography variant="body2" color="text.secondary">
                            Billing Day: {invoice.billing_day_of_month || '-'}
                        </Typography>
                        <Typography variant="body2" color="text.secondary">
                            Router SN: {invoice.customer?.router_sn || '-'}
                        </Typography>
                        <Typography variant="body2" color="text.secondary">
                            Generated By: {invoice.generated_by?.name || '-'}
                        </Typography>
                    </Box>
                </Stack>

                <Table size="small">
                    <TableHead>
                        <TableRow>
                            <TableCell>Description</TableCell>
                            <TableCell>Period</TableCell>
                            <TableCell align="right">Amount</TableCell>
                        </TableRow>
                    </TableHead>
                    <TableBody>
                        <TableRow>
                            <TableCell>{invoice.package_name || 'Monthly internet subscription'}</TableCell>
                            <TableCell>{formatMonth(invoice.invoice_month)}</TableCell>
                            <TableCell align="right">{formatCurrency(invoice.total_amount)}</TableCell>
                        </TableRow>
                    </TableBody>
                </Table>

                <Box sx={{ alignSelf: 'flex-end', width: { xs: '100%', sm: 280 } }}>
                    <Stack spacing={0.75}>
                        <Stack direction="row" justifyContent="space-between">
                            <Typography color="text.secondary">Total</Typography>
                            <Typography sx={{ fontWeight: 760 }}>{formatCurrency(invoice.total_amount)}</Typography>
                        </Stack>
                        <Stack direction="row" justifyContent="space-between">
                            <Typography color="text.secondary">Paid</Typography>
                            <Typography sx={{ fontWeight: 760 }}>{formatCurrency(invoice.paid_amount)}</Typography>
                        </Stack>
                        <Stack direction="row" justifyContent="space-between">
                            <Typography color="text.secondary">Balance</Typography>
                            <Typography sx={{ fontWeight: 860 }}>{formatCurrency(invoice.balance_amount)}</Typography>
                        </Stack>
                    </Stack>
                </Box>

                <Divider />

                <Box>
                    <Typography variant="overline" color="text.secondary">
                        Payment History
                    </Typography>
                    {invoice.payments?.length ? (
                        <Table size="small">
                            <TableHead>
                                <TableRow>
                                    <TableCell>Receipt</TableCell>
                                    <TableCell>Date</TableCell>
                                    <TableCell>Method</TableCell>
                                    <TableCell align="right">Amount</TableCell>
                                </TableRow>
                            </TableHead>
                            <TableBody>
                                {invoice.payments.map((payment) => (
                                    <TableRow key={payment.id}>
                                        <TableCell>{payment.payment_code || '-'}</TableCell>
                                        <TableCell>{formatDate(payment.paid_at)}</TableCell>
                                        <TableCell sx={{ textTransform: 'capitalize' }}>
                                            {String(payment.method || '-').replace('_', ' ')}
                                        </TableCell>
                                        <TableCell align="right">{formatCurrency(payment.amount)}</TableCell>
                                    </TableRow>
                                ))}
                            </TableBody>
                        </Table>
                    ) : (
                        <Typography variant="body2" color="text.secondary">
                            No payments have been applied to this invoice yet.
                        </Typography>
                    )}
                </Box>
            </Stack>
        </PrintLayout>
    );
}
